import { Icon } from '@/types/enums/icon';
import { IconType } from 'react-icons';
import {
  LiaBabySolid,
  LiaBeerSolid,
  LiaBriefcaseSolid,
  LiaCarSolid,
  LiaChartLineSolid,
  LiaCogSolid,
  LiaCreditCardSolid,
  LiaDollarSignSolid,
  LiaEuroSignSolid,
  LiaFileInvoiceSolid,
  LiaFutbolSolid,
  LiaGamepadSolid,
  LiaGiftsSolid,
  LiaGraduationCapSolid,
  LiaHomeSolid,
  LiaLightbulbSolid,
  LiaMobileSolid,
  LiaMoneyCheckAltSolid,
  LiaPawSolid,
  LiaPiggyBankSolid,
  LiaPizzaSliceSolid,
  LiaPlaneDepartureSolid,
  LiaShoppingBasketSolid,
  LiaShoppingCartSolid,
  LiaStethoscopeSolid,
  LiaTheaterMasksSolid,
  LiaTicketAltSolid,
  LiaTintSolid,
  LiaTshirtSolid,
  LiaExchangeAltSolid,
  LiaWifiSolid,
} from 'react-icons/lia';

export const AVAILABLE_ICONS = new Map<Icon, IconType>([
  [Icon.BASKET, LiaShoppingBasketSolid],
  [Icon.BEER, LiaBeerSolid],
  [Icon.BRIEFCASE, LiaBriefcaseSolid],
  [Icon.BULB, LiaLightbulbSolid],
  [Icon.CAR, LiaCarSolid],
  [Icon.CART, LiaShoppingCartSolid],
  [Icon.CHART, LiaChartLineSolid],
  [Icon.COG, LiaCogSolid],
  [Icon.CONTROLLER, LiaGamepadSolid],
  [Icon.CREDIT_CARD, LiaCreditCardSolid],
  [Icon.DOLLAR, LiaDollarSignSolid],
  [Icon.EURO, LiaEuroSignSolid],
  [Icon.FOOTBALL, LiaFutbolSolid],
  [Icon.GIFT, LiaGiftsSolid],
  [Icon.GRADUATION_CAP, LiaGraduationCapSolid],
  [Icon.HOME, LiaHomeSolid],
  [Icon.INTERNET, LiaWifiSolid],
  [Icon.INVOICE, LiaFileInvoiceSolid],
  [Icon.KID, LiaBabySolid],
  [Icon.PAWS, LiaPawSolid],
  [Icon.PAYCHECK, LiaMoneyCheckAltSolid],
  [Icon.PHONE, LiaMobileSolid],
  [Icon.PIGGY_BANK, LiaPiggyBankSolid],
  [Icon.PIZZA, LiaPizzaSliceSolid],
  [Icon.PLANE, LiaPlaneDepartureSolid],
  [Icon.STHETOSCOPE, LiaStethoscopeSolid],
  [Icon.THEATER, LiaTheaterMasksSolid],
  [Icon.TICKET, LiaTicketAltSolid],
  [Icon.TRANSFER, LiaExchangeAltSolid],
  [Icon.TSHIRT, LiaTshirtSolid],
  [Icon.WATER, LiaTintSolid],
]);
