export const SYSTEM_TRANSLATION_KEYS = [
  'TRANSFER.CATEGORY',
  'TRANSFER.IN.SUBCATEGORY',
  'TRANSFER.IN.DESCRIPTION',
  'TRANSFER.OUT.SUBCATEGORY',
  'TRANSFER.OUT.DESCRIPTION',
  'SUBCATEGORY.GENERAL',
];

export const ALLOWED_CURRENCIES = ['ARS', 'EUR', 'USD'];
